#开发环境
spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/articleManagement

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
